### ISSUE TITLE
[DESIGN] Design automated tests (maybe requires : Enforce typing)

### ISSUE THREAD

**Issue by charlottegiseleweil** [ltelab/disdrodb#25]
Do you want us to implement automated tests on new readers provided by the community ? If so, do we need them to add their sample data for a specific reader in order to test it ? We can require them to upload a data_sample at each new reader ..
What do you think ?

**Comment by ghiggi** [comment]
Yes we need to implement tests to validate the generated L0B netCDF data. This is/will be done automatically within the `run_L0` function at the end of processing on the user-side. Incompatibility warnings are already raised during the processing and should also pop up during the reader development if following the provided template. 

Ideally, people can transfer their data to LTE in order to centralize the datasets, together with the metadata YAML files for each station ... which must also adhere to a defined standard to be part of the DISDRODB validated database.

We should discuss if we need a separate repo where we synchronize the metadata of all stations (between users, lab, servers ... ).
Concerning tests, we should implement also pytest check for each function in the repo ... 







Especially
