### ISSUE TITLE
[REFACTOR] L0 readers: replace `raw_dir` and `process_dir` arguments with `base_directory`, `data_source`, `campaign_name`

### ISSUE THREAD

**Issue by charlottegiseleweil** [ltelab/disdrodb#52]
Modify Readers args to enforce folder structure

replace `raw_dir` and `process_dir` arguments of the readers with `base_directory`, `data_source` and `campaign_name`

- keep process_dir as an optional argument in case process_dir is different/outside than base. Rare case. 

/!\ Must update reader_template.py + Tutorial nb + All existing readers.

**Comment by ghiggi** [comment]
I think this could make sense ... but with low priority.
Just to be sure I understand your idea @charlottegiseleweil, do you mean to replace `raw_dir` and `process_dir` arguments of the readers with `base_directory`, `data_source` and `campaign_name` ?
Some points to discuss and clarify:
- `data_source` might be a nicer acronym instead of  `institution_or_country`
- `campaign` or `campaign_name` ?
- `data_folder`, `base_directory`, `base_dir` or `base_dirpath` ? Let's try to define consistent variable names ;) 
- the `base_directory` would have the `raw` and `processed` folder within it? 
- Do you want to impede saving the processed data in a different directory from the parent raw directory (base_directory)?

**Comment by charlottegiseleweil** [comment]
yes to the first question ! clarified issue description accordingly.

I gree with your other suggestions too. I suggest `data_directory`

**Comment by ghiggi** [comment]
Fine with that. Just a last important thought on the following point: 
Now there is a `debug` argument (`True` or `False`) that enable testing the processing of all the archive/readers by loading just a single file (or a few lines) from the raw data of each station. 
When we run that, now we direct all the output to a `/tmp`  trash directory. How do you want to keep this option available given the proposed changes?

**Comment by charlottegiseleweil** [comment]
I assume the `tmp`dir is deleted after the process anyway ? (if it's a trash directory) so it doesn't matter. If this `tmp`directory is not automatically deleted, then I'd suggest it should also be an argument (by default, can just be an directory adjacent to `Processed`).

**Comment by ghiggi** [comment]
We were defining the temporary/trash directory by specifying it in the `processed_dir` argument that you suggest to remove (i.e `processed_dir="/tmp/DISDRODB/DATA_SOURCE/CAMPAIGN_NAME"`)

**Comment by ghiggi** [comment]
Also if this refactoring will not be done, we should soon define a final docstring for all L0 readers and correct the existing ones. 
Currently, all L0 readers still document the wrong raw_dir pattern: `'<...>/disdrodb/data/raw/<campaign_name>' `
See here https://github.com/ltelab/disdrodb/blob/main/disdrodb/L0/readers/EPFL/parser_LOCARNO_2018.py#L54 for example.

And some doc strings still reference the L0 and L1 processing acronyms instead of l0a and l0b. https://github.com/ltelab/disdrodb/blob/main/disdrodb/L0/readers/NCAR/parser_NCAR_EOL_MOBILE.py#L69 

Also, in most cases, the argument description is not consistent with the actual argument name. 
This is almost always the case for the l0a and l0b arguments (which are documented as L0A and L0B). See here for example: https://github.com/ltelab/disdrodb/blob/main/disdrodb/L0/readers/EPFL/parser_EPFL_2009.py#L72
